name: build-app
on: [push]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Select Xcode 15
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
      - uses: actions/checkout@v2
      - run: brew install coreutils gnu-sed nasm ninja
      - name: Build
        run: ./build.sh
      - name: Compress app bundle
        run: xz -z -9 testbox/TES3MP.app
      - name: Save compressed app bundle as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: TES3MP.app.xz
          path: testbox/TES3MP.app.xz
